{{- if .Values.ingress.enabled -}}
  {{- $serviceName := include "siren.fullname" . -}}
  {{- $servicePort := .Values.service.externalPort -}}
  {{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "siren.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
  {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4 }}
  {{- end}}
    run: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- end -}}
